[project]
name = "autopkg-windows"
version = "0.2.0"
description = "Automated Windows Package Tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "inquirerpy>=0.3.4",
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.12.0",
    "ruff>=0.9.0",
]
