[project]
name = "fast-install"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "questionary>=2.1.0",
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.12.0",
    "ruff>=0.9.0",
]
